---
title: AI for Research
listing:
  id: sample-listings
  contents:
    - slides/session_0
    - slides/session_1
    - slides/session_2
    - slides/session_3
    - slides/session_4
    - slides/session_5
  sort: "date"
  fields: [date, title]
  type: table
  filter-ui: false
  sort-ui: false
---



[Full Syllabus](syllabus_2023.pdf)

The objective of the course, will be to explore together through lectures and students
contributions how GPT-4 in particular and Large Language Models (LLMs) in general can be used
for producing research as a substitute to traditional natural language processing techniques
(NLP).

Also, as Large Language Models become more versatile and are being increasingly used to inform
real world decisions, part of the course will be devoted to recent research approaches designed to
experimentally evaluate and practically control the behavior of AI as approximated by an LLM .
We’ll discuss both structural approaches (affecting the model building) and external approaches
(taking AI as a black box and observing its behavior).


## Schedule

::: {#sample-listings}

:::

